### ISSUE TITLE
Use GravApi constants 

### ISSUE THREAD

**Issue by Regaez** [djairhogeuens/grav-plugin-api-git-sync-integrator#1]
[When subscribing to the events here](https://github.com/djairhogeuens/grav-plugin-api-git-sync-integrator/blob/master/api-git-sync-integrator.php#L68-L73), perhaps you could use the `GravApi\Config\Constants` class constants instead of locally declared values?

I don't necessarily foresee them changing in the API plugin (since it would be a breaking change), but since this plugin has a dependency on the API, the class should always be available and it could be a better assurance that this integrator is listening to the correct event names.

**Comment by djairhogeuens** [comment]
@Regaez it was originally put there as locally declared values because of decoupling reasons but that's indeed a bit pointless as the plugin is tightly coupled to the API plugin anyway.

**Comment by Regaez** [comment]
Yeah, it's by no means an essential change to make, but I just thought I'd point out that using the GravApi Constants class could be a possible enhancement.
